### ISSUE TITLE
Code and datasets

### ISSUE THREAD

**Issue by hsywatchingu** [Yuheng-Li/UniversalFakeDetect#1]
Hi yuheng, I am very interested in this work, I would like to ask when the dataset and code of this work will be released, thank you

**Comment by Rohit8y** [comment]
+1

**Comment by chandlerbing65nm** [comment]
where is the official code and dataset?

**Comment by along-river** [comment]
Could you please release the real/fake dataset for the diffusion model? That will be a great help to my work, thank you

**Comment by chandlerbing65nm** [comment]
@Yuheng-Li Please release the dataset and complete the repository!
