### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Koooooba** [Yuheng-Li/UniversalFakeDetect#9]
Could you give me the Pretrained model for a reproduction experiment?

**Comment by uioo1** [comment]
There was the pretrained model but they edited ReadMe file.
[](https://github.com/Yuheng-Li/UniversalFakeDetect/tree/5994c0490d615b92f005ca082ce0f3f03a7b1bbc)

**Comment by ice-pice** [comment]
Still can't find pretrained model weights.
There is a .pth inside pretrained_weights/ folder but it's a 4kb file 

Can we have this model please @utkarshojha ?

**Comment by ice-pice** [comment]
Hey folks, 

- The main feature extractor part of model gets downloaded as you run the validate.py https://github.com/Yuheng-Li/UniversalFakeDetect/blob/main/models/clip/clip.py#L38

- You can find the final fc layers weight in path 'pretrained_weights/fc_weights.pth' 

This issue should be good to close !
